CREATE TABLE "Account" (
  "Id" int NOT NULL IDENTITY(1,1),
  "AccountNumber" varchar(255) DEFAULT NULL,
  "AccountSource" varchar(255) DEFAULT NULL,
  "AnnualRevenue" varchar(255) DEFAULT NULL,
  "BillingCity" varchar(255) DEFAULT NULL,
  "BillingCountry" varchar(255) DEFAULT NULL,
  "BillingPostalCode" varchar(255) DEFAULT NULL,
  "BillingState" varchar(255) DEFAULT NULL,
  "BillingStreet" varchar(255) DEFAULT NULL,
  "Description" varchar(255) DEFAULT NULL,
  "Fax" varchar(255) DEFAULT NULL,
  "Industry" varchar(255) DEFAULT NULL,
  "LastModifiedDate" timestamp NOT NULL,
  "Name" varchar(255) DEFAULT NULL,
  "NumberOfEmployees" integer DEFAULT NULL,
  "Ownership" varchar(255) DEFAULT NULL,
  "Phone" varchar(255) DEFAULT NULL,
  "Rating" varchar(255) DEFAULT NULL,
  "ShippingCity" varchar(255) DEFAULT NULL,
  "ShippingCountry" varchar(255) DEFAULT NULL,
  "ShippingPostalCode" varchar(255) DEFAULT NULL,
  "ShippingState" varchar(255) DEFAULT NULL,
  "ShippingStreet" varchar(255) DEFAULT NULL,
  "Sic" varchar(255) DEFAULT NULL,
  "SicDesc" varchar(255) DEFAULT NULL,
  "Site" varchar(255) DEFAULT NULL,
  "TickerSymbol" varchar(255) DEFAULT NULL,
  "Type" varchar(255) DEFAULT NULL,
  "Website" varchar(255) DEFAULT NULL,
  PRIMARY KEY ("Id")
)